name: Test

on:
  [push]

jobs:
  test: # test 任务可选，视情况而定
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: test
      run: |
        npm i
        npm test